# Generated by Django 3.0.4 on 2020-05-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classfications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classfication', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('sound', models.CharField(max_length=100)),
                ('plain', models.CharField(max_length=100)),
                ('example', models.CharField(max_length=1000, null=True)),
                ('classfication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dire.classfications')),
            ],
        ),
    ]
